from typing import Protocol

from bbf.nodes.expr import (
    Argv,
    ArrayAccess,
    ArrayLiteral,
    Binary,
    BoolFalse,
    BoolTrue,
    FnCall,
    Grouping,
    Identifier,
    IntegerLit,
    StringLit,
    Unary,
)
from bbf.nodes.program import ProgTopLevelStmt
from bbf.nodes.stmt import (
    ArrayAssign,
    Assignment,
    Declaration,
    DoBlock,
    ExprStmt,
    ForStmt,
    IfStmt,
    ReturnStmt,
)
from bbf.nodes.toplevel import FnDef, TopLevelStmt


class Visitor[T](Protocol):
    def visit_identifier(self, identifier: Identifier) -> T: ...
    def visit_integerlit(self, integerlit: IntegerLit) -> T: ...
    def visit_stringlit(self, stringlit: StringLit) -> T: ...
    def visit_binary(self, binary: Binary) -> T: ...
    def visit_unary(self, unary: Unary) -> T: ...
    def visit_grouping(self, grouping: Grouping) -> T: ...
    def visit_argv(self, argv: Argv) -> T: ...
    def visit_fncall(self, fncall: FnCall) -> T: ...
    def visit_array_literal(self, array: ArrayLiteral) -> T: ...
    def visit_array_access(self, array: ArrayAccess) -> T: ...
    def visit_booltrue(self, booltrue: BoolTrue) -> T: ...
    def visit_boolfalse(self, boolfalse: BoolFalse) -> T: ...
    def visit_array_assignment(self, array: ArrayAssign) -> T: ...
    def visit_ifstmt(self, ifstmt: IfStmt) -> T: ...
    def visit_forstmt(self, forstmt: ForStmt) -> T: ...
    def visit_doblock(self, doblock: DoBlock) -> T: ...
    def visit_declaration(self, declaration: Declaration) -> T: ...
    def visit_assignment(self, assignment: Assignment) -> T: ...
    def visit_exprstmt(self, exprstmt: ExprStmt) -> T: ...
    def visit_returnstmt(self, returnstmt: ReturnStmt) -> T: ...
    def visit_fndef(self, fndef: FnDef) -> T: ...
    def visit_toplevelstmt(self, toplevelstmt: TopLevelStmt) -> T: ...
    def visit_progtoplevelstmt(self, progtoplevelstmt: ProgTopLevelStmt) -> T: ...
