from typing import Protocol

from bbf.nodes.expr import (
    Argv,
    Binary,
    FnCall,
    Grouping,
    Identifier,
    IntegerLit,
    StringLit,
    Unary,
)
from bbf.nodes.program import ProgTopLevelStmt
from bbf.nodes.stmt import (
    Assignment,
    Declaration,
    DoBlock,
    ExprStmt,
    ForStmt,
    IfStmt,
    ReturnStmt,
)
from bbf.nodes.toplevel import FnDef, TopLevelStmt


class Visitor(Protocol):
    def visit_identifier(self, identifier: Identifier) -> None: ...
    def visit_integerlit(self, integerlit: IntegerLit) -> None: ...
    def visit_stringlit(self, stringlit: StringLit) -> None: ...
    def visit_binary(self, binary: Binary) -> None: ...
    def visit_unary(self, unary: Unary) -> None: ...
    def visit_grouping(self, grouping: Grouping) -> None: ...
    def visit_argv(self, argv: Argv) -> None: ...
    def visit_fncall(self, fncall: FnCall) -> None: ...
    def visit_ifstmt(self, ifstmt: IfStmt) -> None: ...
    def visit_forstmt(self, forstmt: ForStmt) -> None: ...
    def visit_doblock(self, doblock: DoBlock) -> None: ...
    def visit_declaration(self, declaration: Declaration) -> None: ...
    def visit_assignment(self, assignment: Assignment) -> None: ...
    def visit_exprstmt(self, exprstmt: ExprStmt) -> None: ...
    def visit_returnstmt(self, returnstmt: ReturnStmt) -> None: ...
    def visit_fndef(self, fndef: FnDef) -> None: ...
    def visit_toplevelstmt(self, toplevelstmt: TopLevelStmt) -> None: ...
    def visit_progtoplevelstmt(self, progtoplevelstmt: ProgTopLevelStmt) -> None: ...
