[project]
name = "bbf"
version = "0.3.2"
description = "Compiler for BBF-Lang, a compiled statically-typed language written in Python."
readme = "README.md"
license = "MIT"
authors = [
    { name = "Aaron Bittel", email = "aaron@bittels.de" },
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
bbf = "bbf:main.main"

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "pytest>=8.4.2",
]

[tool.ruff.lint]
select = [
    "E4",
    "E7",
    "E9",
    "F",
    "I",
]
ignore = [
    "E731",
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
pythonpath = [
    "src",
]

[tool.mypy]
warn_return_any = true
warn_unused_configs = true
